#!/usr/bin/env bash

# I want to append the libvirt group to my /etc/group file so I can add my user
# account to them. The groups that are added are listed below this function.
append_group() {
    local group_name="$1"
    if ! grep -q "^$group_name:" /etc/group; then
        echo "Appending $group_name to /etc/group"
        grep "^$group_name:" /usr/lib/group | tee -a /etc/group >/dev/null
    fi
}

# I add my account to the libvirt group so I can create, run, and destroy
# virtual machines.
append_group libvirt
